import os

if os.environ['PLATFORM'] == 'basalt':
    def FlagsForFile(filename, **kwargs):
        return {{
            'flags': [
                '-std=c11',
                '-x',
                'c',
                '-Wall',
                '-Wextra',
                '-Werror',
                '-Wno-unused-parameter',
                '-Wno-error=unused-function',
                '-Wno-error=unused-variable',
                '-I{sdk}/pebble/basalt/include',
                '-I{here}/build',
                '-I{here}',
                '-I{here}/build/src',
                '-I{here}/src',
                '-I{here}/libraries/include',
                '-isystem',
                '{stdlib}',
                '-DRELEASE',
                '-DPBL_PLATFORM_BASALT',
                '-DPBL_COLOR',
                '-DPBL_SDK_3',
                '-DPBL_RECT',
                '-DPBL_COMPASS',
                '-DPBL_HEALTH',
                '-DPBL_SMARTSTRAP',
                '-DPBL_SMARTSTRAP_POWER',
                '-DPBL_MICROPHONE',
                '-D_TIME_H_',
                '-DPBL_DISPLAY_WIDTH=144',
                '-DPBL_DISPLAY_HEIGHT=168',
            ],
            'do_cache': True,
        }}
elif os.environ['PLATFORM'] == 'aplite':
    def FlagsForFile(filename, **kwargs):
        return {{
            'flags': [
                '-std=c11',
                '-x',
                'c',
                '-Wall',
                '-Wextra',
                '-Werror',
                '-Wno-unused-parameter',
                '-Wno-error=unused-function',
                '-Wno-error=unused-variable',
                '-I{sdk}/pebble/aplite/include',
                '-I{here}/build',
                '-I{here}',
                '-I{here}/build/src',
                '-I{here}/src',
                '-I{here}/libraries/include',
                '-isystem',
                '{stdlib}',
                '-DRELEASE',
                '-DPBL_PLATFORM_APLITE',
                '-DPBL_BW',
                '-DPBL_RECT',
                '-DPBL_SDK_3',
                '-DPBL_COMPASS',
                '-DPBL_DISPLAY_WIDTH=144',
                '-DPBL_DISPLAY_HEIGHT=168',
            ],
            'do_cache': True,
        }}
elif os.environ['PLATFORM'] == 'chalk':
    def FlagsForFile(filename, **kwargs):
        return {{
            'flags': [
                '-std=c11',
                '-x',
                'c',
                '-Wall',
                '-Wextra',
                '-Werror',
                '-Wno-unused-parameter',
                '-Wno-error=unused-function',
                '-Wno-error=unused-variable',
                '-I{sdk}/pebble/chalk/include',
                '-I{here}/build',
                '-I{here}',
                '-I{here}/build/src',
                '-I{here}/src',
                '-I{here}/libraries/include',
                '-isystem',
                '{stdlib}',
                '-DRELEASE',
                '-DPBL_PLATFORM_CHALK',
                '-DPBL_COLOR',
                '-DPBL_SDK_3',
                '-DPBL_ROUND',
                '-DPBL_COMPASS',
                '-DPBL_HEALTH',
                '-DPBL_SMARTSTRAP',
                '-DPBL_SMARTSTRAP_POWER',
                '-DPBL_MICROPHONE',
                '-DPBL_DISPLAY_WIDTH=180',
                '-DPBL_DISPLAY_HEIGHT=180',
                '-D_TIME_H_',
            ],
            'do_cache': True,
        }}
elif os.environ['PLATFORM'] == 'diorite':
    def FlagsForFile(filename, **kwargs):
        return {{
            'flags': [
                '-std=c11',
                '-x',
                'c',
                '-Wall',
                '-Wextra',
                '-Werror',
                '-Wno-unused-parameter',
                '-Wno-error=unused-function',
                '-Wno-error=unused-variable',
                '-I{sdk}/pebble/diorite/include',
                '-I{here}/build',
                '-I{here}',
                '-I{here}/build/src',
                '-I{here}/src',
                '-I{here}/libraries/include',
                '-isystem',
                '{stdlib}',
                '-DRELEASE',
                '-DPBL_PLATFORM_DIORITE',
                '-DPBL_BW',
                '-DPBL_SDK_3',
                '-DPBL_RECT',
                '-DPBL_HEALTH',
                '-DPBL_SMARTSTRAP',
                '-DPBL_MICROPHONE',
                '-DPBL_DISPLAY_WIDTH=144',
                '-DPBL_DISPLAY_HEIGHT=168',
                '-D_TIME_H_',
            ],
            'do_cache': True,
        }}
elif os.environ['PLATFORM'] == 'emery':
    def FlagsForFile(filename, **kwargs):
        return {{
            'flags': [
                '-std=c11',
                '-x',
                'c',
                '-Wall',
                '-Wextra',
                '-Werror',
                '-Wno-unused-parameter',
                '-Wno-error=unused-function',
                '-Wno-error=unused-variable',
                '-I{sdk}/pebble/diorite/include',
                '-I{here}/build',
                '-I{here}',
                '-I{here}/build/src',
                '-I{here}/src',
                '-I{here}/libraries/include',
                '-isystem',
                '{stdlib}',
                '-DRELEASE',
                '-DPBL_PLATFORM_EMERY',
                '-DPBL_COLOR',
                '-DPBL_SDK_3',
                '-DPBL_RECT',
                '-DPBL_HEALTH',
                '-DPBL_SMARTSTRAP',
                '-DPBL_MICROPHONE',
                '-DPBL_COMPASS',
                '-DPBL_SMARTSTRAP_POWER',
                '-DPBL_DISPLAY_WIDTH=200',
                '-DPBL_DISPLAY_HEIGHT=228',
                '-D_TIME_H_',
            ],
            'do_cache': True,
        }}
else:
    raise Exception("Need a platform.")
